/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type PidChanged = ContractEventLog<{
  token0: string;
  token1: string;
  pid: string;
  0: string;
  1: string;
  2: string;
}>;

export interface PancakeDepositProxy extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PancakeDepositProxy;
  clone(): PancakeDepositProxy;
  methods: {
    addSupportedTokens(
      tokenA: string,
      tokenB: string,
      pid: number | string | BN
    ): NonPayableTransactionObject<void>;

    depositToFarming(
      tokenA: string,
      tokenB: string,
      amountA: number | string | BN,
      amountB: number | string | BN,
      amountAMin: number | string | BN,
      amountBMin: number | string | BN
    ): NonPayableTransactionObject<void>;

    factory(): NonPayableTransactionObject<string>;

    farming(): NonPayableTransactionObject<string>;

    initialize(
      _farming: string,
      _router: string
    ): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    router(): NonPayableTransactionObject<string>;

    supportedPids(
      arg0: string,
      arg1: string
    ): NonPayableTransactionObject<{
      pair: string;
      pid: string;
      0: string;
      1: string;
    }>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    PidChanged(cb?: Callback<PidChanged>): EventEmitter;
    PidChanged(options?: EventOptions, cb?: Callback<PidChanged>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "PidChanged", cb: Callback<PidChanged>): void;
  once(
    event: "PidChanged",
    options: EventOptions,
    cb: Callback<PidChanged>
  ): void;
}
