/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Vat extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Vat;
  clone(): Vat;
  methods: {
    Line(): NonPayableTransactionObject<string>;

    behalf(bit: string, usr: string): NonPayableTransactionObject<void>;

    cage(): NonPayableTransactionObject<void>;

    can(arg0: string, arg1: string): NonPayableTransactionObject<string>;

    debt(): NonPayableTransactionObject<string>;

    deny(usr: string): NonPayableTransactionObject<void>;

    "file(bytes32,bytes32,uint256)"(
      ilk: string | number[],
      what: string | number[],
      data: number | string | BN
    ): NonPayableTransactionObject<void>;

    "file(bytes32,uint256)"(
      what: string | number[],
      data: number | string | BN
    ): NonPayableTransactionObject<void>;

    flux(
      ilk: string | number[],
      src: string,
      dst: string,
      wad: number | string | BN
    ): NonPayableTransactionObject<void>;

    fold(
      i: string | number[],
      u: string,
      rate: number | string | BN
    ): NonPayableTransactionObject<void>;

    fork(
      ilk: string | number[],
      src: string,
      dst: string,
      dink: number | string | BN,
      dart: number | string | BN
    ): NonPayableTransactionObject<void>;

    frob(
      i: string | number[],
      u: string,
      v: string,
      w: string,
      dink: number | string | BN,
      dart: number | string | BN
    ): NonPayableTransactionObject<void>;

    gem(
      arg0: string | number[],
      arg1: string
    ): NonPayableTransactionObject<string>;

    grab(
      i: string | number[],
      u: string,
      v: string,
      w: string,
      dink: number | string | BN,
      dart: number | string | BN
    ): NonPayableTransactionObject<void>;

    hay(arg0: string): NonPayableTransactionObject<string>;

    heal(rad: number | string | BN): NonPayableTransactionObject<void>;

    hope(usr: string): NonPayableTransactionObject<void>;

    ilks(arg0: string | number[]): NonPayableTransactionObject<{
      Art: string;
      rate: string;
      spot: string;
      line: string;
      dust: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    init(ilk: string | number[]): NonPayableTransactionObject<void>;

    initialize(): NonPayableTransactionObject<void>;

    live(): NonPayableTransactionObject<string>;

    move(
      src: string,
      dst: string,
      rad: number | string | BN
    ): NonPayableTransactionObject<void>;

    nope(usr: string): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    regard(bit: string, usr: string): NonPayableTransactionObject<void>;

    rely(usr: string): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    sin(arg0: string): NonPayableTransactionObject<string>;

    slip(
      ilk: string | number[],
      usr: string,
      wad: number | string | BN
    ): NonPayableTransactionObject<void>;

    suck(
      u: string,
      v: string,
      rad: number | string | BN
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    urns(
      arg0: string | number[],
      arg1: string
    ): NonPayableTransactionObject<{
      ink: string;
      art: string;
      0: string;
      1: string;
    }>;

    vice(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
