/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js';
import type { ContractOptions } from 'web3-eth-contract';
import type {
  Callback,
  NonPayableTransactionObject,
  BaseContract,
} from './types';

export interface WBETH extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): WBETH;
  clone(): WBETH;
  methods: {
    exchangeRate(): NonPayableTransactionObject<string>;
  };
  events: {};
}
